# Generated by Django 2.1.1 on 2018-10-08 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20181004_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='activation_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Registration Tokens',
                'ordering': ['-date'],
                'verbose_name': 'Registration Token',
            },
        ),
    ]
