# Generated by Django 2.1.1 on 2018-10-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_activation_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
