# Generated by Django 2.1.1 on 2018-10-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181008_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation_data',
            name='mobile_number',
            field=models.CharField(default='notSet', max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='activation_data',
            name='status',
            field=models.CharField(default='unverified', max_length=20),
        ),
    ]
