# Generated by Django 2.1.1 on 2018-10-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181009_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation_data',
            name='mobile_number',
            field=models.CharField(default='notSet', max_length=13),
        ),
    ]
