# Generated by Django 2.1.1 on 2018-11-12 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import slugger.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year_founded', models.CharField(max_length=255)),
                ('maximum_members', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('contribution_intervals', models.CharField(max_length=255)),
                ('total_contributions', models.CharField(max_length=255)),
                ('saved_amounts', models.CharField(max_length=255)),
                ('twitter_link', models.CharField(max_length=255)),
                ('facebook_link', models.CharField(max_length=255)),
                ('slug', slugger.fields.AutoSlugField(populate_from='name', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Chamas',
                'verbose_name': 'Chama',
                'ordering': ['-date'],
            },
        ),
    ]
