# Generated by Django 2.1.1 on 2018-12-13 11:33

from django.db import migrations, models
import slugger.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=255)),
                ('year_founded', models.CharField(max_length=255)),
                ('maximum_members', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('contribution_intervals', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly')], max_length=255)),
                ('total_contributions', models.CharField(max_length=255)),
                ('saved_amounts', models.CharField(max_length=255)),
                ('plan_package', models.CharField(max_length=255)),
                ('twitter_link', models.CharField(max_length=255)),
                ('facebook_link', models.CharField(max_length=255)),
                ('slug', slugger.fields.AutoSlugField(populate_from='name', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'chama',
                'verbose_name_plural': 'chamas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='plan_packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'free'), ('starter', 'starter'), ('bronze', 'bronze'), ('silver', 'silver'), ('platinum', 'platinum')], max_length=20)),
                ('chargable', models.BooleanField(default=True)),
                ('charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('maximum_users', models.IntegerField(default=5)),
                ('bulk_emails', models.IntegerField(default=0)),
                ('bulk_sms', models.IntegerField(default=0)),
                ('slug', slugger.fields.AutoSlugField(populate_from='plan_package', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'ordering': ['-date'],
            },
        ),
    ]
