# Generated by Django 2.1.1 on 2018-11-19 22:06

from django.db import migrations, models
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan_packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Free', 'Free'), ('Starter', 'Starter'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Platinum', 'Platinum')], max_length=20)),
                ('chargable', models.BooleanField(default=True)),
                ('charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('maximum_users', models.IntegerField(default=5)),
                ('bulk_emails', models.IntegerField(default=0)),
                ('bulk_sms', models.IntegerField(default=0)),
                ('slug', slugger.fields.AutoSlugField(populate_from='plan_package', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
    ]
