# Generated by Django 2.1.1 on 2018-12-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chama',
            name='plan_package',
            field=models.CharField(choices=[('free', 'free'), ('starter', 'starter'), ('bronze', 'bronze'), ('silver', 'silver'), ('platinum', 'platinum')], max_length=255),
        ),
    ]
