# Generated by Django 2.1.1 on 2018-12-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='africasTalkingResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=13)),
                ('sms_target', models.CharField(max_length=255)),
                ('response_message', models.CharField(max_length=255)),
                ('recipient_status', models.CharField(max_length=255)),
                ('recipient_statusCode', models.CharField(max_length=255)),
                ('recipient_cost', models.CharField(max_length=255)),
                ('recipient_number', models.CharField(max_length=255)),
                ('recipient_messageId', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AfricaStalking SMS Response',
                'verbose_name_plural': 'AfricaStalking SMS Responses',
                'ordering': ['-date'],
            },
        ),
    ]
