# Generated by Django 2.1.1 on 2018-12-14 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='africastalkingresponses',
            old_name='recipient_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='africastalkingresponses',
            old_name='recipient_messageId',
            new_name='messageId',
        ),
        migrations.RenameField(
            model_name='africastalkingresponses',
            old_name='recipient_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='africastalkingresponses',
            old_name='recipient_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='africastalkingresponses',
            old_name='recipient_statusCode',
            new_name='statusCode',
        ),
    ]
