# Generated by Django 2.1.1 on 2018-12-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20181214_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfrikaStalkingSMSMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_target', models.CharField(max_length=100)),
                ('total_sent', models.IntegerField(default=0)),
                ('total_cost', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': 'AfricaStalking SMS Cost Metric',
                'verbose_name_plural': 'AfricaStalking SMS Cost Metrics',
            },
        ),
    ]
